### ISSUE TITLE
Forward to Prowlarr

### ISSUE THREAD

**Issue by chansearrington** [hotio/trackarr#13]
Hey there,

I love the idea for this app, but as I started to set it up, I started to question why I was creating another copy of all my filters and preferences that's separate from all the Arr apps themselves.

So I was wondering if it was possible to just forward all posts to Prowlarr and let it decide if it needs to be downloaded or not?

Is this possible? Pros / Cons?

**Comment by mrhotio** [comment]
This is not the place for support
